version: "3.5"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    volumes:
      - ./db_files:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
